services:
  input-service:
    container_name: input-service
    build:
      context: .
      dockerfile: InputService.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PROCESSING_SERVICE_URL=http://processing-service:4000

  processing-service:
    container_name: processing-service
    build:
      context: .
      dockerfile: ProcessingService.Dockerfile
    ports:
      - "4000:4000"
    environment:
      - WEATHER_API_KEY=.

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
